import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#0d0000",
  },
  mapWrapper: {
    flex: 0,
    height: "65%",
    position: "relative",
  },
  map: {
    flex: 1,
  },

  crosshairDot: {
    position: "absolute",
    top: "50%",
    left: "50%",
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#ffffff",
    borderWidth: 2,
    borderColor: "#dc2626",
    marginTop: -5,
    marginLeft: -5,
  },
  coordsBadge: {
    position: "absolute",
    top: "50%",
    left: "50%",
    marginTop: 25,
    marginLeft: 12,
    backgroundColor: "rgba(0,0,0,0.7)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  coordsText: {
    color: "#f8fafc",
    fontSize: 12,
    fontWeight: "600",
    fontVariant: ["tabular-nums"],
  },
  toggleLabel: {
    color: "#f8fafc",
    fontSize: 12,
    fontWeight: "700",
  },
  fabRow: {
    position: "absolute",
    right: 8,
    flexDirection: "row",
    gap: 8,
  },
  mapBackButton: {
    position: "absolute",
    left: 8,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.75)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
  },
  fabButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.75)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
  },
  fabButtonActive: {
    backgroundColor: "#dc2626",
    borderColor: "rgba(255,255,255,0.3)",
  },
  floatingPanel: {
    position: "absolute",
    right: 8,
    minWidth: 180,
    backgroundColor: "rgba(0,0,0,0.86)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
    padding: 10,
    gap: 8,
  },
  floatingPanelTitle: {
    color: "rgba(248,250,252,0.75)",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  layerOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  layerOptionActive: {
    backgroundColor: "#dc2626",
  },
  layerOptionText: {
    color: "#f8fafc",
    fontSize: 13,
    fontWeight: "700",
  },
  switchRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  listContainer: {
    flex: 1,
    backgroundColor: "#0d0000",
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 4,
  },
  listHeader: {
    color: "rgba(248,250,252,0.6)",
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.5,
    marginBottom: 6,
  },
  listStatus: {
    color: "rgba(248,250,252,0.65)",
    fontSize: 12,
    marginBottom: 8,
  },
  listItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#7a1313",
    borderRadius: 10,
    padding: 7,
    marginBottom: 5,
    gap: 10,
  },
  listItemSelected: {
    backgroundColor: "#dc2626",
    borderWidth: 1.5,
    borderColor: "#ffffff",
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#dc2626",
  },
  dotSelected: {
    backgroundColor: "#ffffff",
  },
  listTitle: {
    color: "#f8fafc",
    fontSize: 13,
    fontWeight: "700",
  },
  listDetail: {
    color: "rgba(248,250,252,0.6)",
    fontSize: 11,
    marginTop: 1,
  },
  routesScreen: {
    flex: 1,
    backgroundColor: "#0d0000",
  },
  routesScreenHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(220,38,38,0.2)",
    gap: 12,
  },
  routesScreenBackBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  routesScreenTitle: {
    flex: 1,
    color: "#f8fafc",
    fontSize: 18,
    fontWeight: "800",
  },
  routesScreenBadge: {
    backgroundColor: "#dc2626",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  routesScreenBadgeText: {
    color: "#f8fafc",
    fontSize: 12,
    fontWeight: "700",
  },
  routesScreenList: {
    flex: 1,
  },
  routesScreenEmpty: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    paddingHorizontal: 40,
  },
  routesScreenEmptyText: {
    color: "rgba(248,250,252,0.4)",
    fontSize: 15,
    textAlign: "center",
    lineHeight: 22,
  },
  routeCard: {
    backgroundColor: "#1a0505",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(220,38,38,0.2)",
    marginBottom: 10,
    overflow: "hidden",
  },
  routeCardExpanded: {
    borderColor: "#dc2626",
  },
  routeCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    gap: 10,
  },
  routeCardName: {
    color: "#f8fafc",
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 2,
  },
  routeCardMeta: {
    color: "rgba(248,250,252,0.55)",
    fontSize: 12,
  },
  routeCardDirections: {
    paddingHorizontal: 14,
    paddingBottom: 14,
    borderTopWidth: 1,
    borderTopColor: "rgba(220,38,38,0.15)",
    paddingTop: 10,
  },
  routeDirectionsLabel: {
    color: "rgba(248,250,252,0.5)",
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.5,
    marginBottom: 8,
  },
  routeDirectionText: {
    color: "#f8fafc",
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 6,
  },
  routesCountFab: {
    height: 40,
    borderRadius: 20,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
    backgroundColor: "#dc2626",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
  },
  routesCountFabText: {
    color: "#f8fafc",
    fontSize: 13,
    fontWeight: "700",
  },
  detailCardOverlay: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#000000",
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 18,
    zIndex: 20,
    alignItems: "flex-start",
  },
  detailCardHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignSelf: "center",
    marginBottom: 14,
  },
  detailCardTitle: {
    color: "#f8fafc",
    fontSize: 20,
    fontWeight: "800",
    marginBottom: 6,
  },
  detailCardDetail: {
    color: "rgba(248,250,252,0.55)",
    fontSize: 14,
    marginBottom: 12,
  },
  detailCardActions: {
    flexDirection: "column",
    gap: 8,
    width: "100%",
  },
  detailCardBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 13,
    borderRadius: 14,
  },
  detailCardBtnPrimary: {
    backgroundColor: "#dc2626",
  },
  detailCardBtnSecondary: {
    backgroundColor: "rgba(255,255,255,0.1)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
  },
  detailCardBtnText: {
    color: "#f8fafc",
    fontSize: 13,
    fontWeight: "700",
  },
  bottomTabs: {
    flexDirection: "row",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 10,
    padding: 3,
    marginBottom: 8,
    gap: 4,
  },
  bottomTab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 7,
    borderRadius: 8,
    gap: 6,
  },
  bottomTabActive: {
    backgroundColor: "#dc2626",
  },
  bottomTabText: {
    color: "rgba(248,250,252,0.5)",
    fontSize: 12,
    fontWeight: "700",
  },
  bottomTabTextActive: {
    color: "#f8fafc",
  },
  tabBadge: {
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 8,
    paddingHorizontal: 5,
    paddingVertical: 1,
  },
  tabBadgeText: {
    color: "#f8fafc",
    fontSize: 10,
    fontWeight: "700",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  modalCard: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderWidth: 1,
    borderBottomWidth: 0,
    padding: 18,
    gap: 8,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "800",
  },
  modalHint: {
    fontSize: 12,
    marginBottom: 6,
  },
  modalLabel: {
    fontSize: 12,
    fontWeight: "600",
    marginTop: 6,
  },
  modalInput: {
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
  },
  modalTextArea: {
    height: 84,
    textAlignVertical: "top",
  },
  categoryChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 2,
  },
  categoryChip: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  categoryChipText: {
    fontSize: 12,
    fontWeight: "600",
  },
  imagePickBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  imagePickBtnText: {
    fontSize: 13,
    fontWeight: "600",
  },
  modalActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 14,
  },
  modalBtn: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  modalBtnText: {
    fontSize: 14,
    fontWeight: "700",
  },
});
